{% set name = "rptools" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name|lower }}
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

requirements:
  host:
    - python {{ python }}
  run:
    - python {{ python }}
    - brs_utils # rpcompletion, rpfba, Args
    - credisdict # rpcompletion, rpfba, rplibs
    - requests # rpcompletion, rpfba, rplibs
    - urllib3 # rpcompletion, rpfba
    - cobra # rpfba, rpextractsink, rplibs
    - timeout-decorator # rpextractsink
    - rdkit # rpextractsink, rplibs
    - python-libsbml # rplibs
    - numpy # rplibs
    - pandas # rplibs, rpthermo
    - scipy # rpthermo
    - equilibrator-api # rpthermo
    # - equilibrator-cache # rpthermo
    - equilibrator-pathway # rpthermo
    - openbabel # rpthermo (equilibrator-assets)
    - redis-py # rplibs
    - colored # rplibs
    - networkx # rplibs
    - networkx >=2.5 # [py==39]
    - filetype  # rplibs (conda-forge)
    - rr_cache # rpcompletion
    - rxn_rebuild # rpcompletion
    - chemlite # rpcompletion ,rpfba, rpthermo
    - h5py # rpscore
    - xgboost # rpscore

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
    - pytest-cov
  commands:
    - python -m {{ name|lower }} --help
    - cd tests ; pytest -v --cov --cov-report term-missing

about:
  home: https://github.com/brsynth/{{ name|lower }}
  summary: {{ data['description'] }}
  license: {{ data.get('license') }}
  license_file: LICENSE

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - breakthewall
