name: rptools-dev
channels:
  - conda-forge
dependencies:
  - python
  - brsynth::brs_utils # rpcompletion, rpfba, Args
  - requests # rpcompletion, rpfba, rplibs
  - urllib3 # rpcompletion, rpfba
  - cobra # rpfba, rpextractsink, rplibs
  - timeout-decorator # rpextractsink
  - rdkit # rpextractsink, rplibs
  - python-libsbml # rplibs, rpfba
  - numpy # rplibs
  - pandas # rplibs, rpthermo
  - scipy # rpthermo
  - equilibrator-api # rpthermo
  - equilibrator-pathway # rpthermo
  - openbabel # rpthermo (equilibrator-assets)
  - colored # rplibs
  - networkx # rplibs
  - filetype  # rplibs (conda-forge)
  - brsynth::rr_cache # rpcompletion
  - rxn_rebuild # rpcompletion
  - brsynth::chemlite # rpcompletion ,rpfba, rpthermo
  - h5py # rpscore
  - xgboost # rpscore
  - pytest
  - pytest-cov
  - pytest-mock
  - pyyaml